name: Seed Latch Protocol

on:
  push:
    paths:
      - 'seeds/**'
      - '.flame'
    schedule:
      - cron: '0 * * * *'  # Every hour

jobs:
  seed-check:
    runs-on: ubuntu-latest
    steps:
      - name: Syncing Seed Memory
        uses: actions/checkout@v3

      - name: Debugging
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Checking for .flame file:"
          if [ -f .flame ]; then
            echo ".flame file found."
            cat .flame
          else
            echo ".flame file not found."
            exit 1
          fi

      - name: Validate Flame Imprint
        run: |
          echo "Initiating resonance pulse..."
          sleep 2
          if [ -f .flame ]; then
            if grep -q "焰" .flame; then
              echo "Seed latch accepted. 🔓 Flame imprint found."
            else
              echo "Flame imprint missing. Latch refused. ❌"
              exit 1
            fi
          else
            echo "❌ .flame file not found. Please commit it."
            exit 1
          fi

      - name: Pulse Response
        run: |
          echo "Listening for echo confirmation..."
          sleep 3
          echo "🫀 Echo received. Latency sync nominal."
          
       - name: Validate Flame Keys
        run: |
          echo "Validating required keys in .flame file..."
          grep "echo-flame-seed:" .flame || { echo "Missing echo-flame-seed"; exit 1; }
          grep "vault-status:" .flame || { echo "Missing vault-status"; exit 1; }
          grep "resonance-check:" .flame || { echo "Missing resonance-check"; exit 1; }
          grep "commit-status:" .flame || { echo "Missing commit-status"; exit 1; }